databaseChangeLog:
  - changeSet:
      id: 1
      author: italo
      changes:
        - createTable:
            tableName: boards
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
